### ISSUE TITLE
SQLITE / CDDA / ps:geometry not detected as geometry in QGIS ?  

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/qgis-ogr-gmlas#2]
ogrinfo return ```Unknown (any)``` for the ```ps:geometry``` element. What does this mean ? mix of geometry types ?

```
ogrinfo GMLAS:inspire/PS/cddaDesignatedArea.gml 
Had to open data source read-only.
INFO: Open of `GMLAS:inspire/PS/cddaDesignatedArea.gml'
      using driver `GMLAS' successful.
1: DesignatedArea (Unknown (any), Point)
```

XML is:

```
 <cdda:DesignatedArea xmlns:cdda="http://dd.eionet.europa.eu/schemaset/cdda" gml:id="CDDA_DESIGNATEDAREA_914f2f5c-2543-43ee-b1c1-ea34fb390d01">
      <ps:geometry xmlns:ps="http://inspire.ec.europa.eu/schemas/ps/4.0">
        <!--Inlined geometry 'CDDA_DESIGNATEDAREA_914f2f5c-2543-43ee-b1c1-ea34fb390d01_PS_GEOMETRY'-->
        <gml:MultiSurface gml:id="CDDA_DESIGNATEDAREA_914f2f5c-2543-43ee-b1c1-ea34fb390d01_PS_GEOMETRY" srsName="EPSG:3035">
          <gml:surfaceMember>
            <gml:Polygon gml:id="GEOMETRY_f30c5f27-79a0-4e81-90fb-84a573308815" srsName="EPSG:3035">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>5164608.520 4005275.591 
...

      <cdda:representativePoint>
        <!--Inlined geometry 'CDDA_DESIGNATEDAREA_914f2f5c-2543-43ee-b1c1-ea34fb390d01_CDDA_REPRESENTATIVEPOINT'-->
        <gml:Point gml:id="CDDA_DESIGNATEDAREA_914f2f5c-2543-43ee-b1c1-ea34fb390d01_CDDA_REPRESENTATIVEPOINT" srsName="EPSG:3035">
          <gml:pos>4004826.202 5165614.536</gml:pos>
        </gml:Point>

```

ogrinfo return information about 2 geometry columns:
```
ogrinfo GMLAS:inspire/PS/cddaDesignatedArea.gml DesignatedArea | more
Had to open data source read-only.
INFO: Open of `GMLAS:inspire/PS/cddaDesignatedArea.gml'
      using driver `GMLAS' successful.

Layer name: DesignatedArea
Geometry (geometry): Unknown (any)
Geometry (representativePoint): Point
Feature Count: 102
Extent (geometry): (1599484.688000, 1104137.264000) - (5549213.592000, 4771645.419000)
Extent (representativePoint): (1112951.366000, 1604132.173000) - (4770638.965000, 5549030.817000)....
Geometry Column 1 = geometry
Geometry Column 2 = representativePoint
```

CDDA (http://dd.eionet.europa.eu/schemas/cdda/CddaReporting_V3.0.xsd) extend PS (http://inspire.ec.europa.eu/schemas/ps/4.0/ProtectedSites.xsd). ```representativePoint``` is properly detected and can be displayed in QGIS. The geometry is visible as an attribute in the attribute table.

![image](https://cloud.githubusercontent.com/assets/1701393/19306206/dc2fc302-9074-11e6-8fe7-5dfaa30243da.png)

But it looks that the geometry is not detected as a polygon layer in QGIS. Same layer in PostGIS, the 2 geometries can be displayed.

![image](https://cloud.githubusercontent.com/assets/1701393/19306347/86b814d2-9075-11e6-8451-8ee8eacafe6a.png)

Issue in sqlite geom type detection ?

**Comment by rouault** [comment]
"Unknown (any)" for the ps:geometry element means that there is no hint in the schema about the particular geometry type . Indeed the declaration in ProtectedSites.xsd is <element name="geometry" type="gml:GeometryPropertyType">. So any geometry type could in theory occur in such columns.

Regarding the QGIS behaviour, when you connect to that database, the spatialite provider proposes 2 layers for the designatedarea, one per geometry column. But there's an error when you connect to the one using the "geometry" column. It is likely it doesn't know how to handle such columns with undetermined geometry  type. In the OGR provider, there's a logic for such columns where it iterates over all the features to determine if there are points, lines or polygons, and expose "sub-layers" for each of them. If you open with Add vector layer, you'll see the polygons of the geometry column (it doesn't propose the sublayer list since there's just one geometry type in that instance). On the other hand, the QGIS OGR provider doesn't currently handle layers with multiple geometry fields, and only propose the first geometry field...

**Comment by fxprunayre** [comment]
> QGIS OGR provider doesn't currently handle layers with multiple geometry fields, and only propose the first geometry field...

Ok got it. Thanks.
